version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"  # Adjust this to daily, monthly, etc., as needed
    groups:
      all-dependencies:
        patterns:
          - "*"  # This wildcard includes all dependencies in one group