skills:
  smelter:
    enabled: true
    maxlevel: 100
    smeltChanceIncreasePerLvl: 0.01
  cave_caller:
    enabled: true
    maxlevel: 250
    caveMonsterHealth: 5.0
    caveMonsterLifespanInSeconds: 15.0